"""Renders Formula/splat.rb for the Homebrew tap from a release tag's source checksum."""

import argparse
from pathlib import Path

TEMPLATE = """# generated by scripts/generate_formula.py, do not edit by hand
class Splat < Formula
  desc "Universal converter and model-backed toolkit for Gaussian splats and images"
  homepage "https://github.com/{repo}"
  url "https://github.com/{repo}/archive/refs/tags/v{version}.tar.gz"
  sha256 "{sha256}"
  license "MIT"

  depends_on arch: :arm64
  depends_on :macos
  depends_on "git" => :build
  depends_on "python@3.12"
  depends_on "uv"

  def install
    ENV["UV_PROJECT_ENVIRONMENT"] = libexec/"venv"
    system "uv", "sync", "--frozen", "--no-dev", "--no-editable",
           "--python", Formula["python@3.12"].opt_bin/"python3.12"
    bin.install_symlink libexec/"venv/bin/splat"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/splat --version")
  end
end
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    for flag in ("version", "repo", "sha256", "out"):
        parser.add_argument(f"--{flag}", required=True)
    args = parser.parse_args()
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(TEMPLATE.format(repo=args.repo, version=args.version, sha256=args.sha256))


if __name__ == "__main__":
    main()
