name: Test

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha }}

      - uses: astral-sh/setup-uv@v5

      - run: uv sync --frozen

      - run: uv run ruff check .

      - run: uv run ruff format --check .

      - run: uv run pytest
